# Generated by Django 5.2.17 on 2026-09-23 06:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, help_text='Application order or invoice reference.', max_length=255, verbose_name='Reference')),
                ('title', models.CharField(help_text='Product or service title displayed on the Bale invoice.', max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Detailed description displayed on the Bale invoice.', verbose_name='Description')),
                ('amount', models.PositiveBigIntegerField(help_text='Amount in Iranian Rials (IRR) processed by Bale.', verbose_name='Amount')),
                ('currency', models.CharField(choices=[('IRR', 'Iranian Rial'), ('IRT', 'Iranian Toman')], default='IRR', help_text='Currency specified when initializing the payment (IRR or IRT).', max_length=4, verbose_name='Currency')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=16, verbose_name='Status')),
                ('chat_id', models.CharField(blank=True, db_index=True, help_text='Bale chat ID where the invoice was sent.', max_length=64, null=True, verbose_name='Chat ID')),
                ('bale_charge_id', models.CharField(blank=True, help_text='Unique payment identifier returned by Bale upon successful payment.', max_length=255, null=True, unique=True, verbose_name='Bale Charge ID')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary custom key-value metadata stored by the application developer.', verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid at')),
            ],
            options={
                'verbose_name': 'Bale Payment',
                'verbose_name_plural': 'Bale Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
